spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medical_logistics
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    contexts: prod
  sql:
    init:
      mode: never
app:
  inbound:
    storage-dir: /var/lib/medical-logistics/inbound-receipts
    default-source-warehouse-code: US-MAIN
    default-receipt-warehouse-code: EDC-NL
    default-receipt-location-code: REC-01



