spring:
  datasource:
    url: jdbc:h2:mem:medical_logistics_api
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    contexts: dev
app:
  inbound:
    storage-dir: ./data/inbound-receipts
    default-source-warehouse-code: US-MAIN
    default-receipt-warehouse-code: EDC-NL
    default-receipt-location-code: REC-01


